import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Header from "@/components/Header/header";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dorinel Rushi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.center}>
          <div className={styles.circle1}></div>
          <div className={styles.circle2}></div>
          <div className={styles.inside}>
            <div className={styles.info}>
              <h4>Hi there 👋 I'm</h4>
              <h1>Dorinel Rushi</h1>
              <p>
                I'm a professional UI/UX designer with Front-end development
                skills based in Albania.
              </p>
              <div className={styles.flexIcon}>
                <Link
                  target="_blank"
                  href="https://www.instagram.com/dorinel.js/"
                >
                  <i className="fa fa-instagram"></i>
                </Link>
                <Link
                  target="_blank"
                  href="https://www.linkedin.com/in/dorinel-rushi-470a9b229/"
                >
                  <i className="fa fa-linkedin"></i>
                </Link>
                <Link target="_blank" href="https://github.com/dorinelrushi">
                  <i className="fa fa-github"></i>
                </Link>
              </div>
            </div>
          </div>
        </div>
        {/*Services*/}
        <div className={styles.gridBox}>
          <Link href="/" className={styles.box}>
            <div className={styles.insideBox}>
              <h2>About</h2>
              <p>Discover my journey: Sharing my experience and skills.</p>
            </div>
          </Link>

          <Link href="/" className={styles.box}>
            <div className={styles.insideBox}>
              <h2>Projects</h2>
              <p>
                Bringing Ideas to Life: A Journey of Collaborating with Various
                Companies to Complete Projects
              </p>
            </div>
          </Link>

          <Link
            target="_blank"
            href="https://www.youtube.com/channel/UC_LUCt_x_bDSPwK60q8TVxA"
            className={styles.box}
          >
            <div className={styles.insideBox}>
              <h2>Tutorials</h2>
              <p>Unleashing My Coding Potential through YouTube Learning</p>
            </div>
          </Link>

          <Link href="/" className={styles.box}>
            <div className={styles.insideBox}>
              <h2>Services</h2>
              <p>
                Offering a wide range of services: Discover the solutions I
                offer
              </p>
            </div>
          </Link>
        </div>
      </main>
    </>
  );
}
